$(document).ready(function(){
  $(".clickable").click(function(){
    $("#initially-showing").fadeToggle();
    $("#initially-hidden").fadeToggle();
  });
  $(".clickable-info").click(function()
  {
    $("#initially-hidden-info").toggle();
    $("#initially-showing-info").toggle();
  })
});
